### ISSUE TITLE
Feature request: passing data with activate()

### ISSUE THREAD

**Issue by domenic** [KenjiBaheux/portals#28] opened 2018-11-15 22:19 UTC
When writing some demo code with portals, we've found it to be very common to need to pass data to a portal "while" activating it.

The ideal syntax for this would be

```js
// outside.js
portal.activate({ some: 'structured cloneable data' });

// inside.js
window.addEventListener("portalactivate", e => {
  console.log(e.data);
});
```

Right now I am emulating it like so: https://gist.github.com/domenic/36cc626e1ed748d26afe6c83ca732ca0 (although I haven't tested that this works as Chrome Canary doesn't have a working portalactivate event yet).

**Comment by ericfs** [comment] 2018-11-16 04:14
I think this is a duplicate of https://github.com/KenjiBaheux/portals/pull/6.

**Comment by domenic** [comment] 2018-11-16 04:30
I guess it is just not in the spec yet?

**Comment by ericfs** [comment] 2018-11-16 04:32
Yeah, I guess so. It only made it in the Explainer:
https://github.com/KenjiBaheux/portals/blob/master/explainer.md#tldr

**Comment by jeremyroman** [comment] 2018-11-20 15:40
One thought while starting to write the spec-ese for this: there isn't an obvious clean way to supply the transfer list, like `postMessage` does. I'm not aware of any precedent for a `{data:foo, dataTransfer:bar}` or similar, but is it okay if you can't send `MessagePort`, transfer an `ArrayBuffer`, etc? That would seem kind of unfortunate.

**Comment by jeremyroman** [comment] 2018-11-20 16:38
Okay, modified the PR to do that.

**Closed** 2018-11-21 16:59 UTC
